### ISSUE TITLE
"Connection refused" as a container, works when manually run

### ISSUE THREAD

**Issue by ShanDestromp** [Roxedus/docker-containers#7]
Per the title, the R-C container fails to start complaining it can't connect with my Radarr install; however if I manually navigate to where the R-C files actually are (`/var/lib/docker/overlay2/...../diff/app`) I can manually invoke the rcm.py file, and point it to the config and have it work as expected.

I don't expect it matters, but I use Portainer to maintain my containers, which uses a docker-compose syntax.  Below is the relevant section.

```
  radarr-collections:
    image: si0972/radarr-collections
    container_name: radarr-collections
    environment:
      PGID: '1001'
      PUID: '1000'
      TZ: America/New_York
      args: '-u -q'
    volumes:
      - /home/dock/config/radarr-collections:/config
```

For giggles, I tried changing the server portion of my rcm.conf file to a variety of options, ranging from hostname, IP, loopback (Radarr is a container on the same host) etc with no effect, and as I mentioned the config works fine when R-C is called externally from docker.

See attached log
[log.txt](https://github.com/Roxedus/docker-containers/files/8308631/log.txt)
